name: counter_weather_bloc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  http: ^1.1.0
  equatable: ^2.0.5
  geolocator: ^10.0.1
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  get_it: ^7.6.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
